services:
  postgres:
    image: "postgres:16"
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mdstore_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  # If you want to use redis instead of cachex, look config/config.exs
  # redis:
  #   image: "redis:7"
  #   restart: on-failure
  #   ports:
  #     - 6379:6379

volumes:
  postgres_data: {}
